[project]
name = "f1-race-analyzer"
version = "0.1.0"
description = "F1 Race Analyzer Web App"
requires-python = ">=3.9"
dependencies = [
    "streamlit",
    "supabase",
    "requests",
    "streamlit-javascript",
    "fastf1",
    "matplotlib",
    "tracker_hub",
]

# 👇 서버의 오해를 풀어주는 마법의 두 줄 추가!
[tool.poetry]
package-mode = false

[tool.uv.sources]
tracker_hub = { git = "https://github.com/gohard-lab/tracker-hub.git" }
